[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = "from_netlify_env"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "from_netlify_env"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "from_netlify_env"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "from_netlify_env"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "from_netlify_env"
  NEXT_PUBLIC_FIREBASE_APP_ID = "from_netlify_env"
  OPENAI_API_KEY = "from_netlify_env"
  ASSEMBLY_AI_API_KEY = "from_netlify_env"
  GOOGLE_CLOUD_PROJECT_ID = "from_netlify_env"
  GOOGLE_CLOUD_CLIENT_EMAIL = "from_netlify_env"
  GOOGLE_CLOUD_PRIVATE_KEY = "from_netlify_env"
  NEXTAUTH_SECRET = "from_netlify_env"
  NEXTAUTH_URL = "from_netlify_env"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(self), geolocation=()"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200